name: GCS Deploy
description: Build and push Ember app to Google Cloud Storage

inputs:
  serviceAccountKey:
    description: The GCP Service Account key used to push on Google Cloud Storage
    required: true
  projectId:
    description: The GCP Project ID where the GCS Bucket lives
    required: true
  bucket:
    description: The Google Cloud Storage bucket where the app lives
    required: true
  algoliaApiKey:
    description: The Algolia API key used by the app
    required: true
  algoliaApp:
    description: The Algolia APP identifier used by the app
    required: true
  cityIndex:
    description: The identifier of the Algolia city index used by the app
    required: true
  mapboxToken:
    description: The MapBox token used by the app
    required: true
  deployment:
    description: Ember deployment name (can be staging or prod)
    required: true

runs:
  using: composite
  steps:
    - name: Prepare env files
      shell: bash
      run: |-
        echo ${{ inputs.serviceAccountKey }} | base64 --decode > key.json

        echo "GCS_PROJECT_ID=${{ inputs.projectId }}" >> .env
        echo "GCLOUD_BUCKET=${{ inputs.bucket }}" >> .env
        echo "ALGOLIA_API_KEY=${{ inputs.algoliaApiKey }}" >> .env
        echo "ALGOLIA_APP=${{ inputs.algoliaApp }}" >> .env
        echo "CITY_INDEX=${{ inputs.cityIndex }}" >> .env
        echo "MAPBOX_TOKEN=${{ inputs.mapboxToken }}" >> .env

    - name: Ember deploy
      shell: bash
      run: |-
        npx ember deploy ${{ inputs.deployment }} --verbose --activate

