name: CI/CD for master branch

on:
  push:
    branches: [ master ]

jobs:

  build-test:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - run: |-
          npx ember test --verbose

  deploy-staging:
    name: Deploy to Staging
    needs: [ build-test ]
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - uses: ./.github/actions/gcs-deploy
        with:
          serviceAccountKey: ${{ secrets.GCP_SA_KEY_GCS_PUSHER_CHEZVOUS }}
          projectId: ${{ secrets.GCS_PROJECT_ID }}
          bucket: ${{ secrets.GCLOUD_BUCKET }}
          algoliaApiKey: ${{ secrets.ALGOLIA_API_KEY }}
          algoliaApp: ${{ secrets.ALGOLIA_APP }}
          cityIndex: ${{ secrets.CITY_INDEX }}
          mapboxToken: ${{ secrets.MAPBOX_TOKEN }}
          deployment: staging
