name: CI/CD for pull requests

on:
  pull_request:

jobs:

  build-test:
    name: Build & Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - run: |-
          npx ember test --verbose
