name: CI/CD for releases

on:
  release:
    types: [ published ]

jobs:

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - uses: ./.github/actions/gcs-deploy
        with:
          serviceAccountKey: ${{ secrets.GCP_SA_KEY_GCS_PUSHER_CHEZVOUS }}
          projectId: ${{ secrets.GCS_PROJECT_ID }}
          bucket: ${{ secrets.GCLOUD_BUCKET }}
          algoliaApiKey: ${{ secrets.ALGOLIA_API_KEY }}
          algoliaApp: ${{ secrets.ALGOLIA_APP }}
          cityIndex: ${{ secrets.CITY_INDEX }}
          mapboxToken: ${{ secrets.MAPBOX_TOKEN }}
          deployment: prod
